const CHANGELOG = [
    // { version: '', log: '' },
    { version: 'v0.19.0', log: 'New Pyre.Object class' },
    { version: 'v0.18.4', log: 'New track for first sector' },
    { version: 'v0.18.3', log: 'Sector only shows on change, debug teleporting' },
    { version: 'v0.18.2', log: 'Sector and subsector names display on transition' },
    { version: 'v0.18.1', log: 'Added sprite for transitions' },
    { version: 'v0.18.0', log: 'World transitions!' },
    { version: 'v0.17.6', log: 'Minor text tweak to intro' },
    { version: 'v0.17.5', log: 'Added text to skip opening cutscene' },
    { version: 'v0.17.4', log: 'Added background panels, render fixes' },
    { version: 'v0.17.3', log: 'Added images to opening cutscene' },
    { version: 'v0.17.2', log: 'Style fixes' },
    { version: 'v0.17.1', log: 'Updated planet name, style tweaks' },
    { version: 'v0.17.0', log: 'Added an opening cutscene' },
    { version: 'v0.16.6', log: 'Added tasteful fade between screens/levels' },
    { version: 'v0.16.5', log: 'Fixed quit/main menu links' },
    { version: 'v0.16.4', log: 'Re-added murderBlock.png' },
    { version: 'v0.16.3', log: 'Removed murderblock.png' },
    { version: 'v0.16.2', log: 'Quit button goes to sharkside homepage' },
    { version: 'v0.16.1', log: 'Main menu background + music, button SFX' },
    { version: 'v0.16.0', log: 'Font now in canvas, background image, various tweaks' },
    { version: 'v0.15.6', log: 'Font and cursor changes, orb total shows' },
    { version: 'v0.15.5', log: 'Health now exists' },
    { version: 'v0.15.4', log: 'Minebots now have activation cues' },
    { version: 'v0.15.3', log: 'Collision effects occur after checks' },
    { version: 'v0.15.2', log: 'Two-frame animated explosions' },
    { version: 'v0.15.1', log: 'Music stays turned off if you refresh' },
    { version: 'v0.15.0', log: 'Enemies, SFX pass for dash, shoot, bullets' },
    { version: 'v0.14.12', log: 'Added SFX for bullet impact' },
    { version: 'v0.14.11', log: 'Fixed murderBlocks' },
    { version: 'v0.14.10', log: 'Fixed reticule... I hope' },
    { version: 'v0.14.9', log: 'Fixed cursors... again' },
    { version: 'v0.14.8', log: 'Fixed cursors for live site' },
    { version: 'v0.14.7', log: 'You start with gun, bulletTime upgrade' },
    { version: 'v0.14.6', log: 'Replaced coins with orbs, bespoke cursor' },
    { version: 'v0.14.5', log: 'Glass panes now break in groups' },
    { version: 'v0.14.4', log: 'Coins now completely fly to you' },
    { version: 'v0.14.3', log: 'Added bullet sprite, low-latency reticule'},
    { version: 'v0.14.2', log: 'Fixed sticky jump, zooming now supported' },
    { version: 'v0.14.1', log: 'Added new level 1' },
    { version: 'v0.14.0', log: 'Added sprites, Pyre.SpriteManager' },
    { version: 'v0.13.6', log: "Excel-edited CSVs break, apparently" },
    { version: 'v0.13.5', log: "Cleaned up Pyre Audio loadBulletTime" },
    { version: 'v0.13.4', log: "Added gun to first level for bullet time demo" },
    { version: 'v0.13.3', log: "Cleaned up the console a bit" },
    { version: 'v0.13.2', log: "Bullet time music" },
    { version: 'v0.13.1', log: "Coins no longer block bullets" },
    { version: 'v0.13.0', log: "Bullet time!" },
    { version: 'v0.12.3', log: "Removed another leading slash" },
    { version: 'v0.12.2', log: "Removed leading slash in file urls" },
    { version: 'v0.12.1', log: "Updated the html file to be index" },
    { version: 'v0.12.0', log: "Moved game to its own repo" },
    { version: 'v0.11.0', log: "Started moving game loop/data to PyreEngine" },
    { version: 'v0.10.3', log: "Updated icon" },
    { version: 'v0.10.2', log: "Added icon for game" },
    { version: 'v0.10.1', log: "Camera boundary fix, coins fly to center" },
    { version: 'v0.10.0', log: "Coins in CSV, collectible upgrades" },
    { version: 'v0.9.11', log: "Dying resets coin counter" },
    { version: 'v0.9.10', log: "Coins fly to player, won't spawn in pairs" },
    { version: 'v0.9.9', log: 'Coins now float pleasingly' },
    { version: 'v0.9.8', log: 'Collected coins now show up in win screen' },
    { version: 'v0.9.7', log: 'Added coins to collect' },
    { version: 'v0.9.6', log: 'Moved objects to their own folder' },
    { version: 'v0.9.5', log: 'Text now appears if you can interact' },
    { version: 'v0.9.4', log: 'You can now Interact with things' },
    { version: 'v0.9.3', log: 'Pyre Vector cache bugfix' },
    { version: 'v0.9.2', log: 'Collision detection optimisation' },
    { version: 'v0.9.1', log: 'The game has an... ending now' },
    { version: 'v0.9.0', log: 'Levels load from CSVs, refactored with Pyre Level' },
    { version: 'v0.8.4', log: 'Added Pyre Level class' },
    { version: 'v0.8.3', log: 'Refactored Audio with Pyre Audio' },
    { version: 'v0.8.2', log: 'Added Pyre Audio class' },
    { version: 'v0.8.1', log: 'Refactored Vector with Pyre Vector' },
    { version: 'v0.8.0', log: 'Added Pyre Vector class' },
    { version: 'v0.7.10', log: 'There are now worlds with 5 levels each' },
    { version: 'v0.7.9', log: 'Toggling music actually does something now' },
    { version: 'v0.7.8', log: 'More music, unique colours for levels' },
    { version: 'v0.7.7', log: 'Camera constraint bug fixes' },
    { version: 'v0.7.6', log: 'Camera constrained to level, pausing quiets music' },
    { version: 'v0.7.5', log: 'Added objectives and level indicator' },
    { version: 'v0.7.4', log: "Glass doesn't vanish when broken, high-vis reticule" },
    { version: 'v0.7.3', log: 'Improved start screen gradient' },
    { version: 'v0.7.2', log: 'Randomised player/goal spawns, no more death spawns' },
    { version: 'v0.7.1', log: 'Movement tweaks for more deliberate play, updated help text' },
    { version: 'v0.7.0', log: 'Added mission grading, scaling levels with more variance' },
    { version: 'v0.6.5', log: 'Timer fix, style overhaul, new font' },
    { version: 'v0.6.4', log: 'In-game timer now pauses correctly' },
    { version: 'v0.6.3', log: 'Added killboxes' },
    { version: 'v0.6.2', log: 'Added a targeting reticule' },
    { version: 'v0.6.1', log: 'Added aiming, UI no longer selectable' },
    { version: 'v0.6.0', log: 'Added a gun =D' },
    { version: 'v0.5.8', log: 'Added glass blocks' },
    { version: 'v0.5.7', log: 'Made music louder' },
    { version: 'v0.5.6', log: 'Tweaks to constants, costume change' },
    { version: 'v0.5.5', log: 'No dash queueing (again), no floor dash spam' },
    { version: 'v0.5.4', log: 'No more dash queueing' },
    { version: 'v0.5.3', log: 'Added restart in case the seed is fucked' },
    { version: 'v0.5.2', log: 'Jump now also antigrav-pack' },
    { version: 'v0.5.1', log: 'Added rudimentary dash upgrade' },
    { version: 'v0.5.0', log: 'Added music and sfx, larger levels with smaller grid' },
    { version: 'v0.4.5', log: 'UI is hidden on win and start menus' },
    { version: 'v0.4.4', log: 'Added some visual flare and an objective' },
    { version: 'v0.4.3', log: 'Added half-baked timer, more constants' },
    { version: 'v0.4.2', log: 'Added sick wall slides, player less sticky' },
    { version: 'v0.4.1', log: 'Collision bugfix, added priority system to renderer' },
    { version: 'v0.4.0', log: 'Random levels, camera tracking' },
    { version: 'v0.3.1', log: 'Screens now use CSS classes' },
    { version: 'v0.3.0', log: 'Added drag, player facing, wall jumping/sticking' },
    { version: 'v0.2.0', log: 'Refactored gameBase, added screens.js and refrences.js' },
    { version: 'v0.1.0', log: 'Refactored screen switching, new version format' },
    { version: 'v0.09', log: 'Added goal, victory screen, game loop' },
    { version: 'v0.08', log: 'Added tolerance for delayed jumps' },
    { version: 'v0.07', log: 'Added debug mode (F4 to toggle), cleaned up input.js' },
    { version: 'v0.06', log: 'Player now collides with walls' },
    { version: 'v0.05', log: 'Player now collides with ceilings' },
    { version: 'v0.04', log: 'Refined player collision, added changelog' },
    { version: 'v0.03', log: 'Added workman/qwerty keyboard layout option' },
    { version: 'v0.02', log: "Added jump lock (so you can only jump once), tweaks to demo level" },
    { version: 'v0.01', log: 'Added version indicator' },
    { version: 'v0.00', log: 'Initial commit, basic platforming' },
]

const VERSION = CHANGELOG[0].version


$version.textContent = "CHANGELOG | "+VERSION
$version.addEventListener('click', () => {
    console.log('%cCHANGELOG', "font-weight: bold; color: lime")

    let bold = "font-weight: bold; color: crimson"
    let normal = "font-weight: normal; color: white"

    for (let i = 0; i < CHANGELOG.length; i++) {
        console.log("%c" + CHANGELOG[i].version + "\n%c" + CHANGELOG[i].log, bold, normal)
    }
    alert("Changelog in the inspector (hit F12 and go to the console).")
})